#!/bin/bash
#
echo -n "Palun sisesta vanus: "
read vanus
if test $vanus -gt 0 -a $vanus -lt 11
then
echo "oled laps"
elif test $vanus -ge 11 -a $vanus -lt 18
then
echo "oled nooruk"
elif test $vanus -ge 18 -a $vanus -lt 63
then
echo "oled taiskasvanud"
elif test $vanus -ge 63
then
echo "oled senior"
else
echo "sisesta korrektne vanus"
fi
