#!/bin/bash
#
echo -n "Reisijate arv: "
read reisijad
echo -n "Kohtade arv bussis: "
read kohad
#
bussid=$(($reisijad / kohad))
ylejaanud=$(($reisijad % $kohad))
if test $ylejaanud -gt 0
then
        bussid=$(($bussid + 1)
fi
echo "Kokku on vaja $bussid bussi!"
